#!/usr/bin/env python
# -*- mode: python; coding: utf-8; -*-

# This file is part of Geeky Notes.
#
# Geeky Notes is a CLI Simplenote client
# <https://github.com/dmych/gn>
# 
# Copyright (c) Dmitri Brechalov, 2010-2011
# 
# Geeky Notes is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Geeky Notes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.

'''gn: Geeky Notes - simplenote CLI client (ver.%s)

Commands:
    $ gn ls            - show list of notes
    $ gn tags          - show tags
    $ gn ls 'tag'      - show notes with the tag
    $ gn [find] 'text' - search for the 'text'
    $ gn [new]         - new note
    $ gn [ed] N        - edit note N
    $ gn rm N          - delete note N
    $ gn sync          - sync with simplenote
    $ gn help          - show this help
'''

import os
import sys
import sync
import db
import api
import re
from config import Config

def error(msg):
    sys.stderr.write('%s\n' % msg)
    sys.exit(1)

def init():
    global notes, keys, config
    config = Config(os.path.expanduser('~/.gn'))
    notes = db.Database()
    keys = notes.keys(sort=True)

def print_note(i):
    note = db.Note(notes, keys[i])
    md = '[%s]' % note.getModifiedFormatted()
    if note._isModified():
	fl = '*'
    else:
	fl = ' '
    print '%4i:%s%s %s %s' % (i, fl, note.getTitle(40).ljust(40), md.rjust(12), note.getTags().decode('utf-8'))

#### cli commands

def help(arg):
    print __doc__ % (api.VERSION)

def synchronize(arg):
    if not (config.has_key('email') or config.has_key('password')):
        error('No simplenote credentials set in config file!')
    if config.has_key('lastsync'):
	since = config['lastsync']
    else:
	since = None
    since = sync.sync(config['email'], config['password'], since)
    config['lastsync'] = since

def show_list(arg):
    found = list()
    for i in range(len(keys)):
        tags = db.Note(notes, keys[i]).tagList()
        if arg is None or arg in tags:
            found.append(i)
    if len(found) == 0:
        print "Not found"
        return
    if arg is not None:
	print 'Notes labeled with the tag "%s":' % arg
    for i in found:
        print_note(i)

def show_tags(arg):
    for tag in notes.tags():
	print tag

def edit(arg):
    TagTemplate = '\n[TAGS]: '
    if arg is not None:
        try:
	    note = db.Note(notes, keys[int(arg)])
        except:
            error('Invalid note number: %s' % arg)
        fname = os.path.join('/tmp', 'geekynote.%s.txt' % arg)
        content = note.getContent().encode('utf-8')
	tags = note.getTags()
	if tags:
	    content += TagTemplate + tags
    else:
        fname = os.path.join('/tmp', 'geekynote.txt')
        content = ''
    fd = open(fname, 'w')
    fd.write(content)
    fd.close()
    mtime = os.path.getmtime(fname)
    edcmd = config['editor']
    if edcmd.find('%s') < 0:
	edcmd += ' %s'
    print '>>>>', edcmd % (fname)
    os.system(edcmd % (fname))
    if mtime != os.path.getmtime(fname):
        if arg is None:
            note = db.Note(notes)
            print 'New note has been created'
	else:
	    print 'The note has been modified!'
	content = open(fname).read()
	try:
	    content, tags = content.split(TagTemplate)
	except:
	    tags = ''
        note.setContent(content)
	note.setTags(tags.strip())
        note.save()
    else:
        print 'Nothing changed'
    os.unlink(fname)

def remove(arg):
    if arg is None:
        error('Note number had not specified!')
    try:
        note = db.Note(notes, keys[int(arg)])
    except:
        error('Invalid note number: %s' % arg)
    note.markDeleted()
    note.save()
    print 'The note %s has been deleted' % arg

def search(arg):
    import re
    found = list()
    for i in range(len(keys)):
        text = db.Note(notes, keys[i]).getContent()
        if re.search(arg, text, re.IGNORECASE) is not None:
            found.append(i)
    if len(found) == 0:
        print "Not found"
        return
    print 'Expression "%s" found in the following notes:' % arg
    for i in found:
        print_note(i)

commands = {
    'ed': edit,
    'new': edit,
    'ls': show_list,
    'tags': show_tags,
    'rm': remove,
    'sync': synchronize,
    'find': search,
    'help': help,
    '-h': help,
    '--help': help,
    }

if __name__ == '__main__':
    init()
    argv = sys.argv[1:]
    if len(argv) == 0:
        cmd = 'new'
        arg = None
    else:
        if argv[0] in commands.keys():
            cmd = argv[0]
            if len(argv) > 1:
                arg = argv[1]
            else:
                arg = None
        else:
            cmd = 'ed'
            arg = argv[0]
            try:
                i = int(arg)
            except:
                cmd = 'find'
    print '>>> command:', cmd, 'arg:', arg, 'function:', commands[cmd]
    commands[cmd](arg)
    
